# Site settings
title: Mariadaria (Marida) K. Ianni-Ravn
author:
  name: Marida Ianni-Ravn
  email: mariadaria@gmail.com
description: PhD Candidate in Human Genetics at The University of Chicago

# Build settings
remote_theme: jekyll/minima
logo: Marida.jpeg
